package com.yiya.bean;

import java.util.Date;
import java.util.List;

public class Weekly {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.id
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private Integer id;
    List<FollowInformation> informations;
    
    
    public List<FollowInformation> getInformations() {
		return informations;
	}

	public void setInformations(List<FollowInformation> informations) {
		this.informations = informations;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.full_customer_name
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String fullCustomerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.main_brand
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String mainBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.subbrand
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String subbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.customer_name
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.post
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.visit_time
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String visitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.visit_content
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String visitContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.classification
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.mediatype
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String mediatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.specific_position
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String specificPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.budget
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.expected_release_date
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String expectedReleaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.remarks
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.next_week_plan
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String nextWeekPlan;

    public String getSpeaker() {
		return speaker;
	}

	public void setSpeaker(String speaker) {
		this.speaker = speaker;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.groupid
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    private String groupid;

    private String speaker;
    
    private Date submissionTime;
    public Date getSubmissionTime() {
		return submissionTime;
	}

	public void setSubmissionTime(Date submissionTime) {
		this.submissionTime = submissionTime;
	}
	 private String industry;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.budget
     *
     * @return the value of weekly.budget
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.classification
     *
     * @return the value of weekly.classification
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.customer_name
     *
     * @return the value of weekly.customer_name
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

 
    public String getExpectedReleaseDate() {
        return expectedReleaseDate;
    }


    public String getFullCustomerName() {
        return fullCustomerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.groupid
     *
     * @return the value of weekly.groupid
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.id
     *
     * @return the value of weekly.id
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.main_brand
     *
     * @return the value of weekly.main_brand
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getMainBrand() {
        return mainBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.mediatype
     *
     * @return the value of weekly.mediatype
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getMediatype() {
        return mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.next_week_plan
     *
     * @return the value of weekly.next_week_plan
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getNextWeekPlan() {
        return nextWeekPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.post
     *
     * @return the value of weekly.post
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getPost() {
        return post;
    }
    	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.remarks
     *
     * @return the value of weekly.remarks
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.specific_position
     *
     * @return the value of weekly.specific_position
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getSpecificPosition() {
        return specificPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.subbrand
     *
     * @return the value of weekly.subbrand
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getSubbrand() {
        return subbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.visit_content
     *
     * @return the value of weekly.visit_content
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getVisitContent() {
        return visitContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.visit_time
     *
     * @return the value of weekly.visit_time
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public String getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.budget
     *
     * @param budget the value for weekly.budget
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setBudget(String budget) {
        this.budget = budget == null ? null : budget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.classification
     *
     * @param classification the value for weekly.classification
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.customer_name
     *
     * @param customerName the value for weekly.customer_name
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.expected_release_date
     *
     * @param expectedReleaseDate the value for weekly.expected_release_date
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setExpectedReleaseDate(String expectedReleaseDate) {
        this.expectedReleaseDate = expectedReleaseDate == null ? null : expectedReleaseDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.full_customer_name
     *
     * @param fullCustomerName the value for weekly.full_customer_name
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setFullCustomerName(String fullCustomerName) {
        this.fullCustomerName = fullCustomerName == null ? null : fullCustomerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.groupid
     *
     * @param groupid the value for weekly.groupid
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.id
     *
     * @param id the value for weekly.id
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.main_brand
     *
     * @param mainBrand the value for weekly.main_brand
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setMainBrand(String mainBrand) {
        this.mainBrand = mainBrand == null ? null : mainBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.mediatype
     *
     * @param mediatype the value for weekly.mediatype
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setMediatype(String mediatype) {
        this.mediatype = mediatype == null ? null : mediatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.next_week_plan
     *
     * @param nextWeekPlan the value for weekly.next_week_plan
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setNextWeekPlan(String nextWeekPlan) {
        this.nextWeekPlan = nextWeekPlan == null ? null : nextWeekPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.post
     *
     * @param post the value for weekly.post
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.remarks
     *
     * @param remarks the value for weekly.remarks
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.specific_position
     *
     * @param specificPosition the value for weekly.specific_position
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setSpecificPosition(String specificPosition) {
        this.specificPosition = specificPosition == null ? null : specificPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.subbrand
     *
     * @param subbrand the value for weekly.subbrand
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setSubbrand(String subbrand) {
        this.subbrand = subbrand == null ? null : subbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.visit_content
     *
     * @param visitContent the value for weekly.visit_content
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setVisitContent(String visitContent) {
        this.visitContent = visitContent == null ? null : visitContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.visit_time
     *
     * @param visitTime the value for weekly.visit_time
     *
     * @mbg.generated Wed Jul 18 14:00:22 CST 2018
     */
    public void setVisitTime(String visitTime) {
        this.visitTime = visitTime;
    }
    
    public String toString() {
		return  "Weekly [id="+id+",Customername="+fullCustomerName+",Sperker="+speaker+"]";
    }
	
	  public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }
}